backend:
  name: git-gateway
  branch: main
  site_domain: ray1e.netlify.app
  use_external_providers: true

publish_mode: editorial_workflow

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "posts"
    label: "Cybersecurity Posts"
    folder: "_posts"
    publish: true
    preview_path: "posts/{{title | slugify}}/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "hidden", default: "0xray1e" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }